// Code generated by command: go run asm.go -out ../dotint8_avx2_amd64.s -stubs ../dotint8_avx2_amd64_stub.go -pkg math. DO NOT EDIT.

package math

func dotInt8AVX2(q []float32, code []int8) float32
