// Code generated by command: go run asm.go -out ../dotint8_avx2_amd64.s -stubs ../dotint8_avx2_amd64_stub.go -pkg math. DO NOT EDIT.

#include "textflag.h"

// func dotInt8AVX2(q []float32, code []int8) float32
// Requires: AVX, AVX2, FMA3, SSE
TEXT ·dotInt8AVX2(SB), NOSPLIT, $0-52
	MOVQ   q_base+0(FP), AX
	MOVQ   code_base+24(FP), CX
	MOVQ   q_len+8(FP), DX
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3

blockloop:
	CMPQ        DX, $0x00000020
	JL          tail
	VPMOVSXBD   (CX), Y4
	VCVTDQ2PS   Y4, Y4
	VFMADD231PS (AX), Y4, Y0
	VPMOVSXBD   8(CX), Y4
	VCVTDQ2PS   Y4, Y4
	VFMADD231PS 32(AX), Y4, Y1
	VPMOVSXBD   16(CX), Y4
	VCVTDQ2PS   Y4, Y4
	VFMADD231PS 64(AX), Y4, Y2
	VPMOVSXBD   24(CX), Y4
	VCVTDQ2PS   Y4, Y4
	VFMADD231PS 96(AX), Y4, Y3
	ADDQ        $0x00000080, AX
	ADDQ        $0x00000020, CX
	SUBQ        $0x00000020, DX
	JMP         blockloop

tail:
	VXORPS X4, X4, X4

tailloop:
	CMPQ        DX, $0x00000000
	JE          reduce
	MOVBLSX     (CX), BX
	VCVTSI2SSL  BX, X5, X5
	VMOVSS      (AX), X6
	VFMADD231SS X6, X5, X4
	ADDQ        $0x00000004, AX
	ADDQ        $0x00000001, CX
	DECQ        DX
	JMP         tailloop

reduce:
	VADDPS       Y0, Y1, Y0
	VADDPS       Y0, Y2, Y0
	VADDPS       Y0, Y3, Y0
	VEXTRACTF128 $0x01, Y0, X1
	VADDPS       X0, X1, X0
	VADDPS       X0, X4, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	MOVSS        X0, ret+48(FP)
	RET
