// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mindb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeleteRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteRequest(buf []byte, offset flatbuffers.UOffsetT) *DeleteRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DeleteRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteRequest) Ids(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *DeleteRequest) IdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DeleteRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeleteRequestAddIds(builder *flatbuffers.Builder, ids flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ids), 0)
}
func DeleteRequestStartIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DeleteRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
