// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mindb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeleteResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteResponse(buf []byte, offset flatbuffers.UOffsetT) *DeleteResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DeleteResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteResponse) DeletedCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeleteResponse) MutateDeletedCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func DeleteResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeleteResponseAddDeletedCount(builder *flatbuffers.Builder, deletedCount int32) {
	builder.PrependInt32Slot(0, deletedCount, 0)
}
func DeleteResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
