// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mindb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InsertRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsInsertRequest(buf []byte, offset flatbuffers.UOffsetT) *InsertRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InsertRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *InsertRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InsertRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InsertRequest) Vectors(obj *Vector, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *InsertRequest) VectorsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func InsertRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InsertRequestAddVectors(builder *flatbuffers.Builder, vectors flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(vectors), 0)
}
func InsertRequestStartVectorsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func InsertRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
