// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mindb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InsertResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsInsertResponse(buf []byte, offset flatbuffers.UOffsetT) *InsertResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InsertResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *InsertResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InsertResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InsertResponse) InsertedCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InsertResponse) MutateInsertedCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func InsertResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InsertResponseAddInsertedCount(builder *flatbuffers.Builder, insertedCount int32) {
	builder.PrependInt32Slot(0, insertedCount, 0)
}
func InsertResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
