// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mindb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SearchRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSearchRequest(buf []byte, offset flatbuffers.UOffsetT) *SearchRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SearchRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SearchRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SearchRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SearchRequest) QueryVector(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *SearchRequest) QueryVectorLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SearchRequest) MutateQueryVector(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *SearchRequest) TopK() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SearchRequest) MutateTopK(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func SearchRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SearchRequestAddQueryVector(builder *flatbuffers.Builder, queryVector flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(queryVector), 0)
}
func SearchRequestStartQueryVectorVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SearchRequestAddTopK(builder *flatbuffers.Builder, topK int32) {
	builder.PrependInt32Slot(1, topK, 0)
}
func SearchRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
