// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mindb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SnapshotResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSnapshotResponse(buf []byte, offset flatbuffers.UOffsetT) *SnapshotResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SnapshotResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SnapshotResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SnapshotResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SnapshotResponse) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SnapshotResponse) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *SnapshotResponse) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SnapshotResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SnapshotResponseAddSuccess(builder *flatbuffers.Builder, success bool) {
	builder.PrependBoolSlot(0, success, false)
}
func SnapshotResponseAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func SnapshotResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
