//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: mindb

package mindb

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for VectorService service
type VectorServiceClient interface{
  Insert(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* InsertResponse, error)  
  Search(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* SearchResponse, error)  
  Delete(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* DeleteResponse, error)  
  Snapshot(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* SnapshotResponse, error)  
}

type vectorServiceClient struct {
  cc *grpc.ClientConn
}

func NewVectorServiceClient(cc *grpc.ClientConn) VectorServiceClient {
  return &vectorServiceClient{cc}
}

func (c *vectorServiceClient) Insert(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* InsertResponse, error) {
  out := new(InsertResponse)
  err := grpc.Invoke(ctx, "/mindb.VectorService/Insert", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

func (c *vectorServiceClient) Search(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* SearchResponse, error) {
  out := new(SearchResponse)
  err := grpc.Invoke(ctx, "/mindb.VectorService/Search", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

func (c *vectorServiceClient) Delete(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* DeleteResponse, error) {
  out := new(DeleteResponse)
  err := grpc.Invoke(ctx, "/mindb.VectorService/Delete", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

func (c *vectorServiceClient) Snapshot(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* SnapshotResponse, error) {
  out := new(SnapshotResponse)
  err := grpc.Invoke(ctx, "/mindb.VectorService/Snapshot", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for VectorService service
type VectorServiceServer interface {
  Insert(context.Context, *InsertRequest) (*flatbuffers.Builder, error)  
  Search(context.Context, *SearchRequest) (*flatbuffers.Builder, error)  
  Delete(context.Context, *DeleteRequest) (*flatbuffers.Builder, error)  
  Snapshot(context.Context, *SnapshotRequest) (*flatbuffers.Builder, error)  
}

func RegisterVectorServiceServer(s *grpc.Server, srv VectorServiceServer) {
  s.RegisterService(&_VectorService_serviceDesc, srv)
}

func _VectorService_Insert_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(InsertRequest)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(VectorServiceServer).Insert(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/mindb.VectorService/Insert",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(VectorServiceServer).Insert(ctx, req.(* InsertRequest))
  }
  return interceptor(ctx, in, info, handler)
}


func _VectorService_Search_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(SearchRequest)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(VectorServiceServer).Search(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/mindb.VectorService/Search",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(VectorServiceServer).Search(ctx, req.(* SearchRequest))
  }
  return interceptor(ctx, in, info, handler)
}


func _VectorService_Delete_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(DeleteRequest)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(VectorServiceServer).Delete(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/mindb.VectorService/Delete",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(VectorServiceServer).Delete(ctx, req.(* DeleteRequest))
  }
  return interceptor(ctx, in, info, handler)
}


func _VectorService_Snapshot_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(SnapshotRequest)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(VectorServiceServer).Snapshot(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/mindb.VectorService/Snapshot",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(VectorServiceServer).Snapshot(ctx, req.(* SnapshotRequest))
  }
  return interceptor(ctx, in, info, handler)
}


var _VectorService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "mindb.VectorService",
  HandlerType: (*VectorServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Insert",
      Handler: _VectorService_Insert_Handler, 
    },
    {
      MethodName: "Search",
      Handler: _VectorService_Search_Handler, 
    },
    {
      MethodName: "Delete",
      Handler: _VectorService_Delete_Handler, 
    },
    {
      MethodName: "Snapshot",
      Handler: _VectorService_Snapshot_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

